github: [odysseu]
ko_fi: odysseu

message: "Thanks for considering to support my property simulator project! Your contribution helps improve the tool, add new features, and keep it accessible for everyone. Together, we can help more people make informed decisions about buying vs. renting. 🏠💸"
